version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: sampleuser
  MYSQL_PASSWORD: samplepassword
  MYSQL_DATABASE: school_db
  REACT_APP_SERVER_PORT: 8000

services:
  mysql-db:
    image: mysql:8.0
    container_name: school_mysql_container
    command: --default-authentication-plugin=mysql_native_password
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3307
    restart: always
    volumes:
      - ./db/school_test_data.sql:/docker-entrypoint-initdb.d/school_test_data.sql
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    container_name: school_phpadmin_container
    environment:
      PMA_HOST: mysql-db
    links:
      - mysql-db:mysql-db
    ports:
      - 8080:80
    restart: always
  server:
    build: ./server
    container_name: school_node_server_container
    depends_on:
      - mysql-db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql-db
    ports:
      - 8000:8000
    volumes:     # connects the local path with the container path and allows nodemon to restart server when server.js is saved saved
      - ./server:/app # but creates a bug where package.json dependencies do not install properly
    links:
      - mysql-db
    command: npm start
  client:
    build: ./client
    container_name: school_client_container
    environment:
      <<: *common-variables
      NODE_PATH: src
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    links:
      - server
    command: npm start